name: CI

on:
  push:
    branches:
      - master

jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.8
      - name: Coverage
        run: |
          npm install
          npm run cov

  publish:
    needs: cov
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.8
      - name: Publish
        run: |
          npm install
          npm run build
          cp package.json ./lib
          cd ./lib
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access public --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
